"""Core module: shared models, exceptions, and logging."""

from architect.core.exceptions import (
    ArchitectBaseError,
    DispatchError,
    ExecuteError,
    FixError,
    GenerateError,
    LLMBudgetExceededError,
    LLMError,
    LLMRateLimitError,
    LLMResponseParseError,
    PlanError,
    UIError,
    ValidationError,
    WorkspaceError,
)
from architect.core.logging import get_logger
from architect.core.models import (
    AgentAssignment,
    AgentCodeOutput,
    ChecklistUpdate,
    Choice,
    CodeFile,
    Decision,
    DiagnosisResult,
    DomainAnalysis,
    ExecuteStateV2,
    FixStrategy,
    GenerateState,
    KnowledgeEntry,
    ModuleDefinition,
    PlanState,
    ReviewResult,
    SharedMemoryUpdate,
    TestFile,
    ValidationResult,
)

__all__ = [
    # Models
    "AgentAssignment",
    "AgentCodeOutput",
    "ChecklistUpdate",
    "Choice",
    "CodeFile",
    "Decision",
    "DiagnosisResult",
    "DomainAnalysis",
    "ExecuteStateV2",
    "FixStrategy",
    "GenerateState",
    "KnowledgeEntry",
    "ModuleDefinition",
    "PlanState",
    "ReviewResult",
    "SharedMemoryUpdate",
    "TestFile",
    "ValidationResult",
    # Exceptions
    "ArchitectBaseError",
    "DispatchError",
    "ExecuteError",
    "FixError",
    "GenerateError",
    "LLMBudgetExceededError",
    "LLMError",
    "LLMRateLimitError",
    "LLMResponseParseError",
    "PlanError",
    "UIError",
    "ValidationError",
    "WorkspaceError",
    # Logging
    "get_logger",
]
